# Generated by Django 4.2.2 on 2023-08-14 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("offer", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="offer",
            name="pub_date",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
