# Generated by Django 4.2.2 on 2023-08-14 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("offer", "0002_offer_pub_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="PhotoAlbum",
            fields=[
                ("image", models.ImageField(upload_to="images/")),
                (
                    "caption",
                    models.CharField(max_length=63, primary_key=True, serialize=False),
                ),
            ],
            options={
                "db_table": "photo_album",
            },
        ),
        migrations.AddField(
            model_name="offer",
            name="discount",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="offer",
            name="images",
            field=models.ManyToManyField(to="offer.photoalbum"),
        ),
    ]
