# Generated by Django 4.2.2 on 2023-08-19 00:33

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("offer", "0003_photoalbum_offer_discount_offer_images"),
    ]

    operations = [
        migrations.CreateModel(
            name="OfferTransDe",
            fields=[
                (
                    "offer_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="offer.offer",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("intro", ckeditor.fields.RichTextField()),
                ("text_field_1", models.CharField(max_length=255)),
                ("text_field_2", models.CharField(max_length=255)),
                ("text_field_3", models.CharField(max_length=255)),
                ("footer", ckeditor.fields.RichTextField()),
            ],
            options={
                "db_table": "offers_de",
            },
        ),
        migrations.CreateModel(
            name="OfferTransEn",
            fields=[
                (
                    "offer_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="offer.offer",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("intro", ckeditor.fields.RichTextField()),
                ("text_field_1", models.CharField(max_length=255)),
                ("text_field_2", models.CharField(max_length=255)),
                ("text_field_3", models.CharField(max_length=255)),
                ("footer", ckeditor.fields.RichTextField()),
            ],
            options={
                "db_table": "offers_en",
            },
        ),
    ]
