# Generated by Django 4.2.2 on 2023-08-20 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("offer", "0004_offertransde_offertransen"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="OfferTransDe",
            new_name="OfferTransIt",
        ),
        migrations.AlterModelTable(
            name="offertransit",
            table="offers_it",
        ),
    ]
