# Generated by Django 4.2.2 on 2023-08-27 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("offer", "0005_rename_offertransde_offertransit_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="offertransen",
            name="duration",
            field=models.CharField(default="1 month", max_length=63),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="offertransit",
            name="duration",
            field=models.CharField(default="1 month", max_length=63),
            preserve_default=False,
        ),
    ]
