# Generated by Django 4.2.2 on 2023-08-14 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("offer", "0002_offer_pub_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="WebManager",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_number", models.CharField(max_length=10)),
                ("clients", models.CharField(max_length=10)),
                ("experience", models.CharField(max_length=10)),
                (
                    "first_offer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="first_offer",
                        to="offer.offer",
                    ),
                ),
                (
                    "second_offer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="second_offer",
                        to="offer.offer",
                    ),
                ),
                (
                    "third_offer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="third_offer",
                        to="offer.offer",
                    ),
                ),
            ],
            options={
                "db_table": "manager_settings",
            },
        ),
    ]
