# Generated by Django 4.2.2 on 2023-06-27 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("requests", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="request",
            name="service",
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name="Service",
        ),
    ]
