# Generated by Django 4.2.2 on 2023-08-14 13:36

import ckeditor.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProjectPortfolio",
            fields=[
                (
                    "project_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("desc", ckeditor.fields.RichTextField(blank=True, null=True)),
                ("pub_date", models.DateTimeField(auto_now=True)),
                ("likes", models.IntegerField(default=0)),
                ("views", models.IntegerField(default=0)),
                ("reposts", models.IntegerField(default=0)),
                ("link", models.URLField(blank=True)),
                ("style", models.CharField(max_length=255)),
                ("type", models.CharField(max_length=255)),
                ("duration", models.DurationField()),
            ],
            options={
                "db_table": "portfolio",
            },
        ),
    ]
