# Generated by Django 4.2.2 on 2023-08-14 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Hashtag",
            fields=[
                ("hashtag_id", models.AutoField(primary_key=True, serialize=False)),
                ("value", models.CharField(max_length=20)),
            ],
            options={
                "db_table": "hashtags",
            },
        ),
        migrations.AddField(
            model_name="projectportfolio",
            name="hashtags",
            field=models.ManyToManyField(to="portfolio.hashtag"),
        ),
    ]
