# Generated by Django 4.2.2 on 2023-08-14 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0002_hashtag_projectportfolio_hashtags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectportfolio",
            name="hashtags",
            field=models.ManyToManyField(blank=True, to="portfolio.hashtag"),
        ),
    ]
