# Generated by Django 4.2.2 on 2023-08-15 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0005_alter_projectportfolio_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectportfolio",
            name="duration",
            field=models.CharField(max_length=20),
        ),
    ]
