# Generated by Django 4.2.2 on 2023-08-19 00:04

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0006_alter_projectportfolio_duration"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectTransEn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("desc", ckeditor.fields.RichTextField()),
                ("style", models.CharField(max_length=255)),
                ("type", models.CharField(max_length=255)),
                (
                    "project_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portfolio.projectportfolio",
                    ),
                ),
            ],
            options={
                "db_table": "portfolio_en",
            },
        ),
        migrations.CreateModel(
            name="ProjectTransDe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("desc", ckeditor.fields.RichTextField()),
                ("style", models.CharField(max_length=255)),
                ("type", models.CharField(max_length=255)),
                (
                    "project_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portfolio.projectportfolio",
                    ),
                ),
            ],
            options={
                "db_table": "portfolio_de",
            },
        ),
    ]
