# Generated by Django 4.2.2 on 2023-08-19 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0007_projecttransen_projecttransde"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="projecttransde",
            name="id",
        ),
        migrations.RemoveField(
            model_name="projecttransen",
            name="id",
        ),
        migrations.AlterField(
            model_name="projecttransde",
            name="project_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to="portfolio.projectportfolio",
            ),
        ),
        migrations.AlterField(
            model_name="projecttransen",
            name="project_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to="portfolio.projectportfolio",
            ),
        ),
    ]
