# Generated by Django 4.2.2 on 2023-08-20 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "portfolio",
            "0008_remove_projecttransde_id_remove_projecttransen_id_and_more",
        ),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ProjectTransDe",
            new_name="ProjectTransIt",
        ),
        migrations.AlterModelTable(
            name="projecttransit",
            table="portfolio_it",
        ),
    ]
