# Generated by Django 4.2.2 on 2023-08-24 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0009_rename_projecttransde_projecttransit_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="hashtag",
            name="value_en",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="hashtag",
            name="value_it",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
