# Generated by Django 4.2.2 on 2023-08-27 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0010_hashtag_value_en_hashtag_value_it"),
    ]

    operations = [
        migrations.AddField(
            model_name="projecttransen",
            name="duration",
            field=models.CharField(default="1 month", max_length=63),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="projecttransit",
            name="duration",
            field=models.CharField(default="1 month", max_length=63),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="projectportfolio",
            name="duration",
            field=models.CharField(max_length=63),
        ),
    ]
