# Generated by Django 4.2.2 on 2023-10-09 14:31

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0011_projecttransen_duration_projecttransit_duration_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectportfolio",
            name="story",
            field=ckeditor.fields.RichTextField(
                default="<p>Default story. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Facilis, temporibus possimus! In quos, architecto sed illum quo ipsa sit harum sunt animi. Rem molestiae esse ut nostrum! Aspernatur, iste enim. Lorem ipsum dolor sit amet consectetur adipisicing elit. Quae mollitia sint iste odit, corrupti cumque illum sunt minus repudiandae alias, eum quas. Ipsa pariatur animi consequatur! Minus molestias corporis natus.</p>"
            ),
        ),
    ]
