# Generated by Django 4.2.2 on 2023-10-09 14:48

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0013_projectportfolio_challenge_projectportfolio_our_work"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="projectportfolio",
            name="duration",
        ),
        migrations.RemoveField(
            model_name="projectportfolio",
            name="link",
        ),
        migrations.RemoveField(
            model_name="projectportfolio",
            name="style",
        ),
        migrations.RemoveField(
            model_name="projectportfolio",
            name="type",
        ),
        migrations.AddField(
            model_name="projectportfolio",
            name="result",
            field=ckeditor.fields.RichTextField(
                default="<p>Default result. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Facilis, temporibus possimus! In quos, architecto sed illum quo ipsa sit harum sunt animi. Rem molestiae esse ut nostrum! Aspernatur, iste enim. Lorem ipsum dolor sit amet consectetur adipisicing elit. Quae mollitia sint iste odit, corrupti cumque illum sunt minus repudiandae alias, eum quas. Ipsa pariatur animi consequatur! Minus molestias corporis natus.</p>"
            ),
        ),
        migrations.AddField(
            model_name="projectportfolio",
            name="value",
            field=ckeditor.fields.RichTextField(
                default="<p>Default value. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Facilis, temporibus possimus! In quos, architecto sed illum quo ipsa sit harum sunt animi. Rem molestiae esse ut nostrum! Aspernatur, iste enim. Lorem ipsum dolor sit amet consectetur adipisicing elit. Quae mollitia sint iste odit, corrupti cumque illum sunt minus repudiandae alias, eum quas. Ipsa pariatur animi consequatur! Minus molestias corporis natus.</p>"
            ),
        ),
    ]
