# Generated by Django 4.2.2 on 2023-10-09 14:58

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0014_remove_projectportfolio_duration_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectportfolio",
            name="scope_list",
            field=ckeditor.fields.RichTextField(
                default="<ul><li>Developing a portal for processes digitalization</li></ul>"
            ),
        ),
    ]
