# Generated by Django 4.2.2 on 2023-10-09 15:32

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0015_projectportfolio_scope_list"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectportfolio",
            name="involvement_list",
            field=ckeditor.fields.RichTextField(
                default="<ul><li>List example, add bullets bellow</li></ul>"
            ),
        ),
        migrations.AddField(
            model_name="projectportfolio",
            name="result_short",
            field=ckeditor.fields.RichTextField(
                default="<p>This is the default short result</p>"
            ),
        ),
        migrations.AddField(
            model_name="projectportfolio",
            name="timeframe_list",
            field=ckeditor.fields.RichTextField(
                default="<ul><li>List example, add bullets bellow</li></ul>"
            ),
        ),
        migrations.AlterField(
            model_name="projectportfolio",
            name="scope_list",
            field=ckeditor.fields.RichTextField(
                default="<ul><li>List example, add bullets bellow</li></ul>"
            ),
        ),
    ]
