# Generated by Django 4.2.2 on 2023-10-09 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0016_projectportfolio_involvement_list_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectportfolio",
            name="tech_stack",
            field=models.CharField(default="Technology1, Technology2", max_length=255),
        ),
    ]
