# Generated by Django 4.2.2 on 2023-10-18 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0017_projectportfolio_tech_stack"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectportfolio",
            name="story_image_1",
            field=models.ImageField(
                default="images/horizontal.jpg", upload_to="images/"
            ),
        ),
    ]
