# Generated by Django 4.2.2 on 2023-10-18 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0018_projectportfolio_story_image_1"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectportfolio",
            name="challenge_image",
            field=models.ImageField(default="images/1.png", upload_to="images/"),
        ),
        migrations.AddField(
            model_name="projectportfolio",
            name="key_image_1",
            field=models.ImageField(default="images/1.png", upload_to="images/"),
        ),
        migrations.AddField(
            model_name="projectportfolio",
            name="key_image_2",
            field=models.ImageField(default="images/1.png", upload_to="images/"),
        ),
        migrations.AddField(
            model_name="projectportfolio",
            name="our_work_1",
            field=models.ImageField(default="images/1.png", upload_to="images/"),
        ),
        migrations.AddField(
            model_name="projectportfolio",
            name="our_work_2",
            field=models.ImageField(default="images/1.png", upload_to="images/"),
        ),
        migrations.AddField(
            model_name="projectportfolio",
            name="story_image_2",
            field=models.ImageField(default="images/1.png", upload_to="images/"),
        ),
        migrations.AddField(
            model_name="projectportfolio",
            name="value_image",
            field=models.ImageField(default="images/1.png", upload_to="images/"),
        ),
    ]
