# Generated by Django 4.2.2 on 2023-10-22 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0019_projectportfolio_challenge_image_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TechBlog",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=63)),
                ("tech1", models.CharField(max_length=63)),
                ("tech2", models.CharField(max_length=63)),
                ("tech3", models.CharField(max_length=63, null=True)),
                ("tech4", models.CharField(max_length=63, null=True)),
            ],
        ),
        migrations.AddField(
            model_name="projectportfolio",
            name="blocks",
            field=models.ManyToManyField(to="portfolio.techblog"),
        ),
    ]
