# Generated by Django 4.2.2 on 2023-10-23 14:56

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0020_techblog_projectportfolio_blocks"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="projectportfolio",
            name="tech_stack",
        ),
        migrations.AddField(
            model_name="projecttransen",
            name="challenge",
            field=ckeditor.fields.RichTextField(
                default="<p>Default challenge ENG. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Facilis, temporibus possimus! In quos, architecto sed illum quo ipsa sit harum sunt animi. Rem molestiae esse ut nostrum! Aspernatur, iste enim. Lorem ipsum dolor sit amet consectetur adipisicing elit. Quae mollitia sint iste odit, corrupti cumque illum sunt minus repudiandae alias, eum quas. Ipsa pariatur animi consequatur! Minus molestias corporis natus.</p>"
            ),
        ),
        migrations.AddField(
            model_name="projecttransen",
            name="involvement_list",
            field=ckeditor.fields.RichTextField(
                default="<ul><li>List example, add bullets bellow</li></ul>"
            ),
        ),
        migrations.AddField(
            model_name="projecttransen",
            name="our_work",
            field=ckeditor.fields.RichTextField(
                default="<p>What we have done ENG. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Facilis, temporibus possimus! In quos, architecto sed illum quo ipsa sit harum sunt animi. Rem molestiae esse ut nostrum! Aspernatur, iste enim. Lorem ipsum dolor sit amet consectetur adipisicing elit. Quae mollitia sint iste odit, corrupti cumque illum sunt minus repudiandae alias, eum quas. Ipsa pariatur animi consequatur! Minus molestias corporis natus.</p>"
            ),
        ),
        migrations.AddField(
            model_name="projecttransen",
            name="result",
            field=ckeditor.fields.RichTextField(
                default="<p>Default result ENG. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Facilis, temporibus possimus! In quos, architecto sed illum quo ipsa sit harum sunt animi. Rem molestiae esse ut nostrum! Aspernatur, iste enim. Lorem ipsum dolor sit amet consectetur adipisicing elit. Quae mollitia sint iste odit, corrupti cumque illum sunt minus repudiandae alias, eum quas. Ipsa pariatur animi consequatur! Minus molestias corporis natus.</p>"
            ),
        ),
        migrations.AddField(
            model_name="projecttransen",
            name="result_short",
            field=ckeditor.fields.RichTextField(
                default="<p>This is the default short result</p>"
            ),
        ),
        migrations.AddField(
            model_name="projecttransen",
            name="scope_list",
            field=ckeditor.fields.RichTextField(
                default="<ul><li>List example, add bullets bellow</li></ul>"
            ),
        ),
        migrations.AddField(
            model_name="projecttransen",
            name="story",
            field=ckeditor.fields.RichTextField(
                default="<p>Default story ENG. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Facilis, temporibus possimus! In quos, architecto sed illum quo ipsa sit harum sunt animi. Rem molestiae esse ut nostrum! Aspernatur, iste enim. Lorem ipsum dolor sit amet consectetur adipisicing elit. Quae mollitia sint iste odit, corrupti cumque illum sunt minus repudiandae alias, eum quas. Ipsa pariatur animi consequatur! Minus molestias corporis natus.</p>"
            ),
        ),
        migrations.AddField(
            model_name="projecttransen",
            name="timeframe_list",
            field=ckeditor.fields.RichTextField(
                default="<ul><li>List example, add bullets bellow</li></ul>"
            ),
        ),
        migrations.AddField(
            model_name="projecttransen",
            name="value",
            field=ckeditor.fields.RichTextField(
                default="<p>Default value ENG. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Facilis, temporibus possimus! In quos, architecto sed illum quo ipsa sit harum sunt animi. Rem molestiae esse ut nostrum! Aspernatur, iste enim. Lorem ipsum dolor sit amet consectetur adipisicing elit. Quae mollitia sint iste odit, corrupti cumque illum sunt minus repudiandae alias, eum quas. Ipsa pariatur animi consequatur! Minus molestias corporis natus.</p>"
            ),
        ),
    ]
