# Generated by Django 4.2.2 on 2023-07-02 10:16

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("art_overview", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="text",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
