# Generated by Django 4.2.2 on 2023-07-03 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("art_overview", "0002_alter_article_text"),
    ]

    operations = [
        migrations.RenameField(
            model_name="article",
            old_name="images",
            new_name="image_main",
        ),
        migrations.AddField(
            model_name="article",
            name="image_secondary",
            field=models.ImageField(default="images/db.png", upload_to="images/"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="article",
            name="is_published",
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
