# Generated by Django 4.2.2 on 2023-07-05 21:39

import art_overview.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("art_overview", "0003_rename_images_article_image_main_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Code",
            fields=[
                (
                    "code",
                    models.CharField(
                        max_length=6,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("articles", models.ManyToManyField(to="art_overview.article")),
            ],
        ),
    ]
