# Generated by Django 4.2.2 on 2023-07-05 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("art_overview", "0004_code"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="code",
            table="codes",
        ),
    ]
