# Generated by Django 4.2.2 on 2023-08-14 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0003_alter_projectportfolio_hashtags"),
        ("art_overview", "0005_alter_code_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="hashtags",
            field=models.ManyToManyField(to="portfolio.hashtag"),
        ),
    ]
