# Generated by Django 4.2.2 on 2023-08-15 14:48

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("art_overview", "0007_article_reposts_article_views"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="footer_text",
            field=ckeditor.fields.RichTextField(
                blank=True, default="This is a default footer"
            ),
        ),
    ]
