# Generated by Django 4.2.2 on 2023-08-18 18:01

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("art_overview", "0009_alter_article_hashtags"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArticleTransEn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("text", ckeditor.fields.RichTextField()),
                ("footer_text", ckeditor.fields.RichTextField()),
                (
                    "article_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translation_en",
                        to="art_overview.article",
                    ),
                ),
            ],
            options={
                "db_table": "articles_en",
            },
        ),
        migrations.CreateModel(
            name="ArticleTransDe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("text", ckeditor.fields.RichTextField()),
                ("footer_text", ckeditor.fields.RichTextField()),
                (
                    "article_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translation_de",
                        to="art_overview.article",
                    ),
                ),
            ],
            options={
                "db_table": "articles_de",
            },
        ),
    ]
