# Generated by Django 4.2.2 on 2023-08-19 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("art_overview", "0010_articletransen_articletransde"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="articletransde",
            name="id",
        ),
        migrations.RemoveField(
            model_name="articletransen",
            name="id",
        ),
        migrations.AlterField(
            model_name="articletransde",
            name="article_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                related_name="translation_de",
                serialize=False,
                to="art_overview.article",
            ),
        ),
        migrations.AlterField(
            model_name="articletransen",
            name="article_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                related_name="translation_en",
                serialize=False,
                to="art_overview.article",
            ),
        ),
    ]
