# Generated by Django 4.2.2 on 2023-08-20 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "art_overview",
            "0011_remove_articletransde_id_remove_articletransen_id_and_more",
        ),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ArticleTransDe",
            new_name="ArticleTransIt",
        ),
        migrations.AlterModelTable(
            name="articletransit",
            table="articles_it",
        ),
    ]
