# Generated by Django 4.2.2 on 2023-08-25 08:47

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("art_overview", "0012_rename_articletransde_articletransit_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="bottom_text",
            field=ckeditor.fields.RichTextField(
                default="This is a default bottom text"
            ),
        ),
    ]
